name: Update the Gradle Wrapper

on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Update the Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
