name: Update the Gradle Wrapper

on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Switch to Java 17
        run: echo "JAVA_HOME=$JAVA_HOME_17_X64"
      - name: Update the Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
